[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "This is a button"
LANDING_DESCRIPTION = "GM-Vault"
LANDING_PAGE = "home"
LANDING_TITLE = "GM Vault"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/lakotelman/GM-Vault"
SITE_TITLE = "All you need to know about your world"
SITE_TITLE_TAB = "GM Vault"
SITE_URL = "https://gm-vault.netlify.app"
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
GANALYTICS = ""
SLUGIFY = ""
HOME_GRAPH = ""
PAGE_GRAPH = ""
SIDEBAR_COLLAPSED = ""
FOOTER = ""
ROOT_SECTION_NAME = "main"
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """